### ISSUE TITLE
HTML Injection Warning

### ISSUE THREAD

**Issue by BD103** [Conner1115/replverse#3]
Hello,

That chat feature is wonderful, but it has a security flaw. It does not escape the `<` and `>` signs when messages are sent. This means that anyone could write a message like `Hello, <span style="color: green">world!</span>` and it would output the rendered HTML. I have done some testing, and it doesn't seem to do too much harm. (I put these messages in `#html-css` since it seemed to fit.)

![html injection 1](https://user-images.githubusercontent.com/59022059/153113163-2baa9949-17ce-49c0-9690-07c0b673c4e1.png)

All visual HTML tags seem to work, though thankfully `<script>` and `<style>` didn't run.

As a solution to use, I recommend either using [HTML-Escaper](https://www.npmjs.com/package/html-escaper) or [Escape-HTML](https://www.npmjs.com/package/escape-html). HTML-Escaper is more recent of a project, but Escape-HTML is more used. Your choice. 😄 

Anyways, I hope you don't mind me playing around with this new feature. (I may submit a PR if you ask, though I'm a bit rusty with JS.)

~BD103

**Comment by Conner1115** [comment]
That's how markdown is supposed to work.  It's okay as long as people can't use javascript to mess things up.

**Comment by BD103** [comment]
Cool, just making sure you are aware. :)
